#!/bin/sh

echo "testing now..."
echo "========================================"
storybook_container_state=$(
  cd infra/ && \
  docker compose ps \
    --format json | jq -r '.[] | select(.Name == "infra-storybook-1").State'
)
if [ "$storybook_container_state" != "running" ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ Storybook container is not running, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

(CI=true make test) &
jest_test_pid=$!

(CI=true make test-storybook) &
storybook_test_pid=$!

wait $jest_test_pid
if [ $? -ne 0 ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ Tests failed, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

wait $storybook_test_pid
if [ $? -ne 0 ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ Storybook tests failed, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

echo "========================================"
