/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Attendance,
  AttendanceClockIn,
  AttendanceClockOut,
  AttendanceRemarks,
  HTTPValidationError,
} from '../models';
import {
    AttendanceFromJSON,
    AttendanceToJSON,
    AttendanceClockInFromJSON,
    AttendanceClockInToJSON,
    AttendanceClockOutFromJSON,
    AttendanceClockOutToJSON,
    AttendanceRemarksFromJSON,
    AttendanceRemarksToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface ReadAttendancesAttendancesStaffIdWorkDateGetRequest {
    staffId: number;
    workDate: number;
}

export interface RegisterClockInAttendancesStaffIdWorkDateClockInPostRequest {
    staffId: number;
    workDate: number;
    attendanceClockIn: AttendanceClockIn;
}

export interface RegisterClockOutAttendancesStaffIdWorkDateClockOutPatchRequest {
    staffId: number;
    workDate: number;
    attendanceClockOut: AttendanceClockOut;
}

export interface RegisterRemarksAttendancesStaffIdWorkDateRemarksPatchRequest {
    staffId: number;
    workDate: number;
    attendanceRemarks: AttendanceRemarks;
}

/**
 * 
 */
export class AttendanceApi extends runtime.BaseAPI {

    /**
     * 指定したIDの勤怠情報を取得します。
     * スタッフIDで勤怠情報を取得
     */
    async readAttendancesAttendancesStaffIdWorkDateGetRaw(requestParameters: ReadAttendancesAttendancesStaffIdWorkDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Attendance>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling readAttendancesAttendancesStaffIdWorkDateGet.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling readAttendancesAttendancesStaffIdWorkDateGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/attendances/{staff_id}/{work_date}`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttendanceFromJSON(jsonValue));
    }

    /**
     * 指定したIDの勤怠情報を取得します。
     * スタッフIDで勤怠情報を取得
     */
    async readAttendancesAttendancesStaffIdWorkDateGet(requestParameters: ReadAttendancesAttendancesStaffIdWorkDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Attendance> {
        const response = await this.readAttendancesAttendancesStaffIdWorkDateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 出勤方法は、`通常`と`直行`の2つ方法で登録することができます。<br>         <br>         **通常**<br>         通常でリクエストする場合は、`start_time`を指定してください。<br>         `go_directly_flag`は自動で`false`として処理されます。<br>         <br>         **直行**<br>         直行でリクエストする場合は、`go_directly_flag`を`true`にしてください。<br>         `start_time`は自動で`09:00:00`として処理されます。<br>
     * 出勤
     */
    async registerClockInAttendancesStaffIdWorkDateClockInPostRaw(requestParameters: RegisterClockInAttendancesStaffIdWorkDateClockInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Attendance>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling registerClockInAttendancesStaffIdWorkDateClockInPost.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling registerClockInAttendancesStaffIdWorkDateClockInPost.');
        }

        if (requestParameters.attendanceClockIn === null || requestParameters.attendanceClockIn === undefined) {
            throw new runtime.RequiredError('attendanceClockIn','Required parameter requestParameters.attendanceClockIn was null or undefined when calling registerClockInAttendancesStaffIdWorkDateClockInPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/attendances/{staff_id}/{work_date}/clock_in`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttendanceClockInToJSON(requestParameters.attendanceClockIn),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttendanceFromJSON(jsonValue));
    }

    /**
     * 出勤方法は、`通常`と`直行`の2つ方法で登録することができます。<br>         <br>         **通常**<br>         通常でリクエストする場合は、`start_time`を指定してください。<br>         `go_directly_flag`は自動で`false`として処理されます。<br>         <br>         **直行**<br>         直行でリクエストする場合は、`go_directly_flag`を`true`にしてください。<br>         `start_time`は自動で`09:00:00`として処理されます。<br>
     * 出勤
     */
    async registerClockInAttendancesStaffIdWorkDateClockInPost(requestParameters: RegisterClockInAttendancesStaffIdWorkDateClockInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Attendance> {
        const response = await this.registerClockInAttendancesStaffIdWorkDateClockInPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 退勤方法は、`通常`と`直帰`の2つの方法で登録することができます。<br>         <br>         **通常**<br>         通常でリクエストする場合は、`end_time`を指定してください。<br>         `return_directly_flag`は自動で`false`として処理されます。<br>         <br>         **直帰**<br>         直帰でリクエストする場合は、`return_direct_flag`を`true`にしてください。<br>         `start_time`は自動で`09:00:00`として処理されます。<br>
     * 退勤時刻を登録
     */
    async registerClockOutAttendancesStaffIdWorkDateClockOutPatchRaw(requestParameters: RegisterClockOutAttendancesStaffIdWorkDateClockOutPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Attendance>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling registerClockOutAttendancesStaffIdWorkDateClockOutPatch.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling registerClockOutAttendancesStaffIdWorkDateClockOutPatch.');
        }

        if (requestParameters.attendanceClockOut === null || requestParameters.attendanceClockOut === undefined) {
            throw new runtime.RequiredError('attendanceClockOut','Required parameter requestParameters.attendanceClockOut was null or undefined when calling registerClockOutAttendancesStaffIdWorkDateClockOutPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/attendances/{staff_id}/{work_date}/clock_out`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AttendanceClockOutToJSON(requestParameters.attendanceClockOut),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttendanceFromJSON(jsonValue));
    }

    /**
     * 退勤方法は、`通常`と`直帰`の2つの方法で登録することができます。<br>         <br>         **通常**<br>         通常でリクエストする場合は、`end_time`を指定してください。<br>         `return_directly_flag`は自動で`false`として処理されます。<br>         <br>         **直帰**<br>         直帰でリクエストする場合は、`return_direct_flag`を`true`にしてください。<br>         `start_time`は自動で`09:00:00`として処理されます。<br>
     * 退勤時刻を登録
     */
    async registerClockOutAttendancesStaffIdWorkDateClockOutPatch(requestParameters: RegisterClockOutAttendancesStaffIdWorkDateClockOutPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Attendance> {
        const response = await this.registerClockOutAttendancesStaffIdWorkDateClockOutPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 備考を登録します。<br>
     * 備考を登録
     */
    async registerRemarksAttendancesStaffIdWorkDateRemarksPatchRaw(requestParameters: RegisterRemarksAttendancesStaffIdWorkDateRemarksPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Attendance>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling registerRemarksAttendancesStaffIdWorkDateRemarksPatch.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling registerRemarksAttendancesStaffIdWorkDateRemarksPatch.');
        }

        if (requestParameters.attendanceRemarks === null || requestParameters.attendanceRemarks === undefined) {
            throw new runtime.RequiredError('attendanceRemarks','Required parameter requestParameters.attendanceRemarks was null or undefined when calling registerRemarksAttendancesStaffIdWorkDateRemarksPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/attendances/{staff_id}/{work_date}/remarks`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AttendanceRemarksToJSON(requestParameters.attendanceRemarks),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttendanceFromJSON(jsonValue));
    }

    /**
     * 備考を登録します。<br>
     * 備考を登録
     */
    async registerRemarksAttendancesStaffIdWorkDateRemarksPatch(requestParameters: RegisterRemarksAttendancesStaffIdWorkDateRemarksPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Attendance> {
        const response = await this.registerRemarksAttendancesStaffIdWorkDateRemarksPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
