/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Rest,
  RestEnd,
  RestStart,
} from '../models';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RestFromJSON,
    RestToJSON,
    RestEndFromJSON,
    RestEndToJSON,
    RestStartFromJSON,
    RestStartToJSON,
} from '../models';

export interface ReadRestRestsStaffIdWorkDateGetRequest {
    staffId: number;
    workDate: number;
}

export interface RegisterEndRestRestsStaffIdWorkDateEndPatchRequest {
    staffId: number;
    workDate: number;
    restEnd: RestEnd;
}

export interface RegisterStartRestRestsStaffIdWorkDateStartPostRequest {
    staffId: number;
    workDate: number;
    restStart: RestStart;
}

/**
 * 
 */
export class RestApi extends runtime.BaseAPI {

    /**
     * 指定したIDと勤務日の休憩情報を取得します。
     * 休憩情報を取得
     */
    async readRestRestsStaffIdWorkDateGetRaw(requestParameters: ReadRestRestsStaffIdWorkDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Rest>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling readRestRestsStaffIdWorkDateGet.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling readRestRestsStaffIdWorkDateGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rests/{staff_id}/{work_date}`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RestFromJSON(jsonValue));
    }

    /**
     * 指定したIDと勤務日の休憩情報を取得します。
     * 休憩情報を取得
     */
    async readRestRestsStaffIdWorkDateGet(requestParameters: ReadRestRestsStaffIdWorkDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Rest> {
        const response = await this.readRestRestsStaffIdWorkDateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 休憩を終了します。<br>
     * 休憩終了
     */
    async registerEndRestRestsStaffIdWorkDateEndPatchRaw(requestParameters: RegisterEndRestRestsStaffIdWorkDateEndPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Rest>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling registerEndRestRestsStaffIdWorkDateEndPatch.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling registerEndRestRestsStaffIdWorkDateEndPatch.');
        }

        if (requestParameters.restEnd === null || requestParameters.restEnd === undefined) {
            throw new runtime.RequiredError('restEnd','Required parameter requestParameters.restEnd was null or undefined when calling registerEndRestRestsStaffIdWorkDateEndPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rests/{staff_id}/{work_date}/end`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RestEndToJSON(requestParameters.restEnd),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RestFromJSON(jsonValue));
    }

    /**
     * 休憩を終了します。<br>
     * 休憩終了
     */
    async registerEndRestRestsStaffIdWorkDateEndPatch(requestParameters: RegisterEndRestRestsStaffIdWorkDateEndPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Rest> {
        const response = await this.registerEndRestRestsStaffIdWorkDateEndPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 休憩を開始します。<br>
     * 休憩開始
     */
    async registerStartRestRestsStaffIdWorkDateStartPostRaw(requestParameters: RegisterStartRestRestsStaffIdWorkDateStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Rest>> {
        if (requestParameters.staffId === null || requestParameters.staffId === undefined) {
            throw new runtime.RequiredError('staffId','Required parameter requestParameters.staffId was null or undefined when calling registerStartRestRestsStaffIdWorkDateStartPost.');
        }

        if (requestParameters.workDate === null || requestParameters.workDate === undefined) {
            throw new runtime.RequiredError('workDate','Required parameter requestParameters.workDate was null or undefined when calling registerStartRestRestsStaffIdWorkDateStartPost.');
        }

        if (requestParameters.restStart === null || requestParameters.restStart === undefined) {
            throw new runtime.RequiredError('restStart','Required parameter requestParameters.restStart was null or undefined when calling registerStartRestRestsStaffIdWorkDateStartPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rests/{staff_id}/{work_date}/start`.replace(`{${"staff_id"}}`, encodeURIComponent(String(requestParameters.staffId))).replace(`{${"work_date"}}`, encodeURIComponent(String(requestParameters.workDate))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestStartToJSON(requestParameters.restStart),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RestFromJSON(jsonValue));
    }

    /**
     * 休憩を開始します。<br>
     * 休憩開始
     */
    async registerStartRestRestsStaffIdWorkDateStartPost(requestParameters: RegisterStartRestRestsStaffIdWorkDateStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Rest> {
        const response = await this.registerStartRestRestsStaffIdWorkDateStartPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
