/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceRemarks
 */
export interface AttendanceRemarks {
    /**
     * 
     * @type {string}
     * @memberof AttendanceRemarks
     */
    remarks: string;
}

/**
 * Check if a given object implements the AttendanceRemarks interface.
 */
export function instanceOfAttendanceRemarks(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "remarks" in value;

    return isInstance;
}

export function AttendanceRemarksFromJSON(json: any): AttendanceRemarks {
    return AttendanceRemarksFromJSONTyped(json, false);
}

export function AttendanceRemarksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceRemarks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remarks': json['remarks'],
    };
}

export function AttendanceRemarksToJSON(value?: AttendanceRemarks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remarks': value.remarks,
    };
}

