/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceClockOut
 */
export interface AttendanceClockOut {
    /**
     * 
     * @type {string}
     * @memberof AttendanceClockOut
     */
    endTime: string;
    /**
     * 
     * @type {boolean}
     * @memberof AttendanceClockOut
     */
    returnDirectlyFlag: boolean;
}

/**
 * Check if a given object implements the AttendanceClockOut interface.
 */
export function instanceOfAttendanceClockOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "endTime" in value;
    isInstance = isInstance && "returnDirectlyFlag" in value;

    return isInstance;
}

export function AttendanceClockOutFromJSON(json: any): AttendanceClockOut {
    return AttendanceClockOutFromJSONTyped(json, false);
}

export function AttendanceClockOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceClockOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endTime': json['end_time'],
        'returnDirectlyFlag': json['return_directly_flag'],
    };
}

export function AttendanceClockOutToJSON(value?: AttendanceClockOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end_time': value.endTime,
        'return_directly_flag': value.returnDirectlyFlag,
    };
}

