/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceClockIn
 */
export interface AttendanceClockIn {
    /**
     * 
     * @type {string}
     * @memberof AttendanceClockIn
     */
    startTime: string;
    /**
     * 
     * @type {boolean}
     * @memberof AttendanceClockIn
     */
    goDirectlyFlag: boolean;
}

/**
 * Check if a given object implements the AttendanceClockIn interface.
 */
export function instanceOfAttendanceClockIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "goDirectlyFlag" in value;

    return isInstance;
}

export function AttendanceClockInFromJSON(json: any): AttendanceClockIn {
    return AttendanceClockInFromJSONTyped(json, false);
}

export function AttendanceClockInFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceClockIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': json['start_time'],
        'goDirectlyFlag': json['go_directly_flag'],
    };
}

export function AttendanceClockInToJSON(value?: AttendanceClockIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_time': value.startTime,
        'go_directly_flag': value.goDirectlyFlag,
    };
}

