/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonthlyAttendance
 */
export interface MonthlyAttendance {
    /**
     * 
     * @type {number}
     * @memberof MonthlyAttendance
     */
    staffId: number;
    /**
     * 
     * @type {Date}
     * @memberof MonthlyAttendance
     */
    targetDate: Date;
    /**
     * 
     * @type {number}
     * @memberof MonthlyAttendance
     */
    workTotal: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlyAttendance
     */
    workDays: number;
}

/**
 * Check if a given object implements the MonthlyAttendance interface.
 */
export function instanceOfMonthlyAttendance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "staffId" in value;
    isInstance = isInstance && "targetDate" in value;
    isInstance = isInstance && "workTotal" in value;
    isInstance = isInstance && "workDays" in value;

    return isInstance;
}

export function MonthlyAttendanceFromJSON(json: any): MonthlyAttendance {
    return MonthlyAttendanceFromJSONTyped(json, false);
}

export function MonthlyAttendanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyAttendance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'staffId': json['staff_id'],
        'targetDate': (new Date(json['target_date'])),
        'workTotal': json['work_total'],
        'workDays': json['work_days'],
    };
}

export function MonthlyAttendanceToJSON(value?: MonthlyAttendance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'staff_id': value.staffId,
        'target_date': (value.targetDate.toISOString().substr(0,10)),
        'work_total': value.workTotal,
        'work_days': value.workDays,
    };
}

