/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestStart
 */
export interface RestStart {
    /**
     * 
     * @type {string}
     * @memberof RestStart
     */
    startTime: string;
}

/**
 * Check if a given object implements the RestStart interface.
 */
export function instanceOfRestStart(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "startTime" in value;

    return isInstance;
}

export function RestStartFromJSON(json: any): RestStart {
    return RestStartFromJSONTyped(json, false);
}

export function RestStartFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestStart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': json['start_time'],
    };
}

export function RestStartToJSON(value?: RestStart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_time': value.startTime,
    };
}

