/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestEnd
 */
export interface RestEnd {
    /**
     * 
     * @type {string}
     * @memberof RestEnd
     */
    endTime: string;
}

/**
 * Check if a given object implements the RestEnd interface.
 */
export function instanceOfRestEnd(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "endTime" in value;

    return isInstance;
}

export function RestEndFromJSON(json: any): RestEnd {
    return RestEndFromJSONTyped(json, false);
}

export function RestEndFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestEnd {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endTime': json['end_time'],
    };
}

export function RestEndToJSON(value?: RestEnd | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end_time': value.endTime,
    };
}

