/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Rest
 */
export interface Rest {
    /**
     * 
     * @type {number}
     * @memberof Rest
     */
    restTimeId: number;
    /**
     * 
     * @type {number}
     * @memberof Rest
     */
    parentRestTimeId?: number;
    /**
     * 
     * @type {number}
     * @memberof Rest
     */
    staffId: number;
    /**
     * 
     * @type {Date}
     * @memberof Rest
     */
    workDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Rest
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Rest
     */
    endTime?: Date;
}

/**
 * Check if a given object implements the Rest interface.
 */
export function instanceOfRest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "restTimeId" in value;
    isInstance = isInstance && "staffId" in value;
    isInstance = isInstance && "workDate" in value;
    isInstance = isInstance && "startTime" in value;

    return isInstance;
}

export function RestFromJSON(json: any): Rest {
    return RestFromJSONTyped(json, false);
}

export function RestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'restTimeId': json['rest_time_id'],
        'parentRestTimeId': !exists(json, 'parent_rest_time_id') ? undefined : json['parent_rest_time_id'],
        'staffId': json['staff_id'],
        'workDate': (new Date(json['work_date'])),
        'startTime': (new Date(json['start_time'])),
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
    };
}

export function RestToJSON(value?: Rest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rest_time_id': value.restTimeId,
        'parent_rest_time_id': value.parentRestTimeId,
        'staff_id': value.staffId,
        'work_date': (value.workDate.toISOString().substring(0,10)),
        'start_time': (value.startTime.toISOString()),
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
    };
}

