/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
} from './Role';

/**
 * 
 * @export
 * @interface StaffRole
 */
export interface StaffRole {
    /**
     * 
     * @type {number}
     * @memberof StaffRole
     */
    roleId: number;
    /**
     * 
     * @type {number}
     * @memberof StaffRole
     */
    staffId: number;
    /**
     * 
     * @type {Role}
     * @memberof StaffRole
     */
    role: Role;
}

/**
 * Check if a given object implements the StaffRole interface.
 */
export function instanceOfStaffRole(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "roleId" in value;
    isInstance = isInstance && "staffId" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function StaffRoleFromJSON(json: any): StaffRole {
    return StaffRoleFromJSONTyped(json, false);
}

export function StaffRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
        'staffId': json['staff_id'],
        'role': RoleFromJSON(json['role']),
    };
}

export function StaffRoleToJSON(value?: StaffRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role_id': value.roleId,
        'staff_id': value.staffId,
        'role': RoleToJSON(value.role),
    };
}

