/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffUpdate
 */
export interface StaffUpdate {
    /**
     * 
     * @type {string}
     * @memberof StaffUpdate
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof StaffUpdate
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StaffUpdate
     */
    mailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof StaffUpdate
     */
    iconPath?: string;
}

/**
 * Check if a given object implements the StaffUpdate interface.
 */
export function instanceOfStaffUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "mailAddress" in value;

    return isInstance;
}

export function StaffUpdateFromJSON(json: any): StaffUpdate {
    return StaffUpdateFromJSONTyped(json, false);
}

export function StaffUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastName': json['last_name'],
        'firstName': json['first_name'],
        'mailAddress': json['mail_address'],
        'iconPath': !exists(json, 'icon_path') ? undefined : json['icon_path'],
    };
}

export function StaffUpdateToJSON(value?: StaffUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last_name': value.lastName,
        'first_name': value.firstName,
        'mail_address': value.mailAddress,
        'icon_path': value.iconPath,
    };
}

