/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffRoleUpdate
 */
export interface StaffRoleUpdate {
    /**
     * 
     * @type {number}
     * @memberof StaffRoleUpdate
     */
    roleId: number;
}

/**
 * Check if a given object implements the StaffRoleUpdate interface.
 */
export function instanceOfStaffRoleUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "roleId" in value;

    return isInstance;
}

export function StaffRoleUpdateFromJSON(json: any): StaffRoleUpdate {
    return StaffRoleUpdateFromJSONTyped(json, false);
}

export function StaffRoleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffRoleUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleId': json['role_id'],
    };
}

export function StaffRoleUpdateToJSON(value?: StaffRoleUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role_id': value.roleId,
    };
}

