/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Staff
 */
export interface Staff {
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    mailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    iconPath?: string;
    /**
     * 
     * @type {number}
     * @memberof Staff
     */
    staffId: number;
}

/**
 * Check if a given object implements the Staff interface.
 */
export function instanceOfStaff(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "mailAddress" in value;
    isInstance = isInstance && "staffId" in value;

    return isInstance;
}

export function StaffFromJSON(json: any): Staff {
    return StaffFromJSONTyped(json, false);
}

export function StaffFromJSONTyped(json: any, ignoreDiscriminator: boolean): Staff {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastName': json['last_name'],
        'firstName': json['first_name'],
        'mailAddress': json['mail_address'],
        'iconPath': !exists(json, 'icon_path') ? undefined : json['icon_path'],
        'staffId': json['staff_id'],
    };
}

export function StaffToJSON(value?: Staff | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last_name': value.lastName,
        'first_name': value.firstName,
        'mail_address': value.mailAddress,
        'icon_path': value.iconPath,
        'staff_id': value.staffId,
    };
}

