/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkPeriodPerMonth
 */
export interface WorkPeriodPerMonth {
    /**
     * 
     * @type {Date}
     * @memberof WorkPeriodPerMonth
     */
    targetMonth: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkPeriodPerMonth
     */
    jobStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkPeriodPerMonth
     */
    jobEndDate: Date;
    /**
     * 
     * @type {number}
     * @memberof WorkPeriodPerMonth
     */
    workPeriodPerMonthId: number;
}

/**
 * Check if a given object implements the WorkPeriodPerMonth interface.
 */
export function instanceOfWorkPeriodPerMonth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "targetMonth" in value;
    isInstance = isInstance && "jobStartDate" in value;
    isInstance = isInstance && "jobEndDate" in value;
    isInstance = isInstance && "workPeriodPerMonthId" in value;

    return isInstance;
}

export function WorkPeriodPerMonthFromJSON(json: any): WorkPeriodPerMonth {
    return WorkPeriodPerMonthFromJSONTyped(json, false);
}

export function WorkPeriodPerMonthFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkPeriodPerMonth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'targetMonth': (new Date(json['target_month'])),
        'jobStartDate': (new Date(json['job_start_date'])),
        'jobEndDate': (new Date(json['job_end_date'])),
        'workPeriodPerMonthId': json['work_period_per_month_id'],
    };
}

export function WorkPeriodPerMonthToJSON(value?: WorkPeriodPerMonth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'target_month': (value.targetMonth.toISOString()),
        'job_start_date': (value.jobStartDate.toISOString()),
        'job_end_date': (value.jobEndDate.toISOString()),
        'work_period_per_month_id': value.workPeriodPerMonthId,
    };
}

