/* tslint:disable */
/* eslint-disable */
/**
 * クラウド勤怠システム
 *  社内向けの勤怠管理システムです。 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkPeriodPerMonthCreate
 */
export interface WorkPeriodPerMonthCreate {
    /**
     * 
     * @type {Date}
     * @memberof WorkPeriodPerMonthCreate
     */
    targetMonth: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkPeriodPerMonthCreate
     */
    jobStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkPeriodPerMonthCreate
     */
    jobEndDate: Date;
}

/**
 * Check if a given object implements the WorkPeriodPerMonthCreate interface.
 */
export function instanceOfWorkPeriodPerMonthCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "targetMonth" in value;
    isInstance = isInstance && "jobStartDate" in value;
    isInstance = isInstance && "jobEndDate" in value;

    return isInstance;
}

export function WorkPeriodPerMonthCreateFromJSON(json: any): WorkPeriodPerMonthCreate {
    return WorkPeriodPerMonthCreateFromJSONTyped(json, false);
}

export function WorkPeriodPerMonthCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkPeriodPerMonthCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'targetMonth': (new Date(json['target_month'])),
        'jobStartDate': (new Date(json['job_start_date'])),
        'jobEndDate': (new Date(json['job_end_date'])),
    };
}

export function WorkPeriodPerMonthCreateToJSON(value?: WorkPeriodPerMonthCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'target_month': (value.targetMonth.toISOString()),
        'job_start_date': (value.jobStartDate.toISOString()),
        'job_end_date': (value.jobEndDate.toISOString()),
    };
}

